#
# Gallery configuration
#
# Don't edit this file, edit /config.local-prod.yml or /config.local-dev.yml instead.
#

parameters:
        gallery:
                name: "%kernel.hostname%"
                root_breadcrumb: "%kernel.hostname%"
                path_prefix: "%kernel.root_dir%/data/gallery/"
                url_prefix: "/"
                dav_url_prefix: "webdavs://gallery.frozen-doe.net/dav/"
                index_file: "data/gallery/index.list"
                url_thumbnail_ext: ".tb.jpg"
                resize_mode: "same_height"
                thumbnail_size: 160
                date_format: "Y-m-d"
                datetime_format: "Y-m-d H:i:s"

framework:
        assets: false
        php_errors:
                log: true
        router:
                resource: "%kernel.root_dir%/app/config/routing.yml"
                strict_requirements: ~
        secret: "" # read-only website
        templating:
                engines: [ 'twig', 'php' ]

twig:
        debug: "%kernel.debug%"
        strict_variables: "%kernel.debug%"
        paths:
                - "%kernel.root_dir%/app/views"
        globals:
                gallery: "%gallery%"

services:

