index:
        path: /
        defaults:
                _controller: "Gallery\\Controller\\GalleryController::indexAction"

list:
        path: /ls/{list}
        defaults:
                _controller: "Gallery\\Controller\\GalleryController::indexAction"
        requirements:
                list: '^[a-z0-9-]+$'

gallery:
        path: /{gallery}/
        defaults:
                _controller: "Gallery\\Controller\\GalleryController::galleryAction"

gallery-path:
        path: /{gallery}/{path}
        defaults:
                _controller: "Gallery\\Controller\\GalleryController::galleryAction"
        requirements:
                path: ".*"

