<?php
/*
 * Copyright (c) 2017, Josef Kufner  <josef@kufner.cz>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

namespace Gallery;

class Assets
{
	public static function installSymlink()
	{
		$config = __DIR__ . '/../../web/assets.config.yml';
		$assets_target = '../app/assets';
		$assets_dir = __DIR__ . '/../../web/';
		$assets_url = '/';
		$assets_link_name = 'assets.%s';

		echo "Installing assets symlink\n";

		// Remove old symlinks
		$pattern = sprintf($assets_link_name, '*');
		foreach (scandir($assets_dir) as $old_symlink) {
			$fn = $assets_dir.$old_symlink;
			if (fnmatch($pattern, $old_symlink) && is_link($fn)) {
				echo "  - unlink: ", $fn, "\n";
				unlink($fn);
			}
		}

		// Generate token
		$link_name = sprintf($assets_link_name, time());
		$symlink = $assets_dir.$link_name;
		$url = $assets_url.$link_name;

		// Create new symlink
		echo "  - new symlink: ", $symlink, "\n";
		symlink($assets_target, $symlink);

		// Store symlink name in config file
		echo "  - generate config: ", $config, "\n";
		file_put_contents($config,
			 "# This file is generated by ".__FILE__."\n"
			."# Do not edit!\n"
			."parameters:\n"
			."  assets_url: ".$url."\n");
	}

}

